AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hawk Logger Lambda for Alexa Skill using OpenAI and MongoDB

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 256

Resources:
  HawkLoggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          OPENAI_API_KEY: <Your open API key>
          MONGODB_URI: mongodb+srv://<auth info>@cluster0.fuy8oaz.mongodb.net/
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
